### ISSUE TITLE
Team training: WordPress

### ISSUE THREAD

**Issue by apiluso-gov** [bcgov/cleanbc#105]
**As a [description of user]?**
As a member of the CleanBC DX team (Umbrella and GE/BH streams)

**I want to [functionality]**
a training sessions with Nate King re. WordPress back-end on navigation and content editing 

**So that [benefit]**
I will be able to go in and create content edits as required in preparation for user testing (May 17/18) and beyond.

**Additional context**
There's a lot of content that needs to be updated in WP; will need more than 1 person helping out. Some team members may not be present, so recording the session is a good move for now and for later (when training other Gov stakeholders like EMLI for GE/BH projects)

**Acceptance Criteria**
- [x] Meg to reach out to Nate King to arrange
- [x] Date/time confirmed with Nate King (Week of May 2/9)
- [x] Meeting recorded for posterity
- [x] Basic how-to notes generated and made available to the team for quick guidance

**Comment by codewisenate** [comment]
Please set up training at your convenience with key stakeholders. I will prioritise it in my schedule for whatever works best for the group.

**Comment by meg-stiven** [comment]
@apiluso-gov here's the list of attendees for this: 

- Meg
- April
- Harry
- Amanda
- Audrey (if it's next week, if we can get it in this week, she can watch the recording)
- Aude
- Laura

Anyone I've missed?

**Comment by meg-stiven** [comment]
We'll plan for Vandna to watch the recording when she's back.

**Comment by apiluso-gov** [comment]
@meg-stiven  sounds good. The invite list looks complete to me.

I've confirmed with Nate that the meeting will last 2 hours.There is no wide availability for a 2-hour session in folks' calendars for this week; I have scheduled training for Monday May 9 1pm-3pm.

**Comment by meg-stiven** [comment]
Thanks @apiluso-gov. We'll need to hold time for edits to be made May 10-12 then. I'll follow up in a teams chat about this.
