### ISSUE TITLE
Test plan

### ISSUE THREAD

**Issue by meg-stiven** [bcgov/cleanbc#13]
**As a [description of user]?**
user researcher, stakeholder, product owner

**I want to [functionality]**
understand the plan for testing the Go Electric site before launch

**So that [benefit]**
I can feel confident that the site design and functionality will be validated with users before launch, and issues found in testing will be actioned.

**Acceptance Criteria**
- [x] includes test goals, methods, participants, reporting format (how test findings will be shared and actioned)
- [x] draft to be reviewed by Meg
- [x] draft to be reviewed by Audrey
- [x] plan revised

**Related Resources**
* Test Plan [https://bcgov.sharepoint.com/:w:/t/04504/EVqkokqBzThAhsrTNxCYv50BuoWOeSLi3yPHq87omx2XWQ?e=wAPnTa]

**Comment by meg-stiven** [comment]
@apiluso-gov Thanks for getting this together so quickly. I've reviewed and made a few comments in the doc. Looks great overall. Happy with the goals and methods - well targeted. Appreciate how you've laid out risks, assumptions, tools needed. 

I'd like to review the moderators guide when that section is complete.

**Comment by apiluso-gov** [comment]
@meg-stiven The test script is drafted and ready for your review (as much as it can be - I can't write the section for the Income Testing App until I can see what it looks like; I'll reach out to Audrey separately about this.
