### ISSUE TITLE
Pull request code review

### ISSUE THREAD

**Issue by codewisenate** [bcgov/cleanbc#133]
@codewisenate will submit a PR request for a code review which is required for approval of the theme by GDX dev team. 

Once the theme has been developed in full, the Pull Request process is required in order for the GDX dev team to review and ensure the theme development is not a risk and can be supported by the GDX team. Once approved the development branch will be committed to the Main branch for the theme and versioned to 1.0.0.

**Comment by meg-stiven** [comment]
@codewisenate could you estimate this ticket? 
@sid - I think we may need to add this one to Sprint Birch

**Comment by codewisenate** [comment]
Initial Pull Request was made June 1. Code review followed and theme was approved. There is still an outstanding final PR with some changes required but I am waiting on that as there may be additional style updates required for the Vehicle app page, yet to be identified by Harry. Once I have those requirements in the code base I will do a final test and commit followed by the v1.0.0 PR. As the intent to go into production is set for June 27 or later there is time for further tweaks as needed before I make the final commit and PR.

**Comment by codewisenate** [comment]
Pull Request approved and theme merged to development branch. Code review complete.
