### ISSUE TITLE
Finalizing the GCPE/EMLI edits before implementation

### ISSUE THREAD

**Issue by sidbhaskara** [bcgov/cleanbc#19]
**As a [description of user]?**
As a EMLI/GCPE

**I want to [functionality]**
discuss edits that are rejected and understand why, resolve conflicts if any

**So that [benefit]**
there's agreement on the edits before they are made

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Meeting with the core team, GCPE, EMLI to review the edits spreadsheet
- Agreement given by both

**Comment by apuns** [comment]
Summarized in GE teams channel, @meg-stiven you can close this if you're comfy
