### ISSUE TITLE
Archive & remove duplicate content on gov

### ISSUE THREAD

**Issue by apuns** [bcgov/cleanbc#209]
**When [Situation]?**
Prepping to launch the new GE Wordpress site

**I want to [Motivation]**
Make sure folks have a single source of information

**So I can [Expected Outcome]**
connect them with the info they need!

**Context**
Pages needing to be removed:

- https://www2.gov.bc.ca/gov/content?id=E4CA2456E602413DA4BAEF48D7FC1F95

- https://www2.gov.bc.ca/gov/content?id=C3C09B8F1F98401B8B62CF92CCCEC694

- https://www2.gov.bc.ca/gov/content?id=45ADAA3F2FA5489EBF7AD9D0621565D3

- https://www2.gov.bc.ca/gov/content?id=A98E5DFE21E84A5C852AF0C840495D83

- https://www2.gov.bc.ca/gov/content?id=31AD51FBB1944490A0EE677CEEFBAB19

**Comment by apuns** [comment]
Docs are in review, actual archiving and removal actions TBD

**Comment by apuns** [comment]
Met with Christina and Audrey today and made some changes based on their feedback. back with them for review.

**Comment by sidbhaskara** [comment]
Hi @apuns, can we close this?

**Comment by apuns** [comment]
Yes!

Cheers,

Amanda
she/her
This email was sent from the traditional, ancestral and unceded territory of the Coast Salish peoples–Sḵwx̱wú7mesh (Squamish), Stó:lō and Səl̓ílwətaʔ/Selilwitulh (Tsleil-Waututh) and xʷməθkʷəy̓əm (Musqueam) Nations.


From: sidbhaskara ***@***.***>
Reply-To: bcgov/cleanbc ***@***.***>
Date: Tuesday, August 9, 2022 at 8:31 AM
To: bcgov/cleanbc ***@***.***>
Cc: "Punshon, Amanda CITZ:EX" ***@***.***>, Mention ***@***.***>
Subject: Re: [bcgov/cleanbc] Archive & remove duplicate content on gov (Issue #209)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


Hi @apuns<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapuns&data=05%7C01%7Camanda.punshon%40gov.bc.ca%7C7eaf91d1756f4ca2649e08da7a1c3007%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637956558725557762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Hy%2BWOGrpveX3wSOZgX9ZqukdmUM5JhmK0Sj5V9bXPjU%3D&reserved=0>, can we close this?
