### ISSUE TITLE
Pre-Launch coordination for Go electric production

### ISSUE THREAD

**Issue by sidbhaskara** [bcgov/cleanbc#223]
**As a [description of user]?**
As a 

**I want to [functionality]**
A clear and concise description of what you want to happen. Ex. I want to share my feedback about climate topics with government online [...]

**So that [benefit]**
How will this benefit the overall product goal?

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Nate to coordinate with Jeff on moving that development site into production day of.

**Comment by codewisenate** [comment]
I have briefed Jeff that the site will go into production on June 27 at the earliest. My current information has this happening "June 27 or later" so I have let him know there is some uncertainty regarding the actual timing. Once we have a firm date I will follow up with him to schedule in something more exact.
