### ISSUE TITLE
Connect with CAS Engagement & Web Team

### ISSUE THREAD

**Issue by hebertlaura** [bcgov/cleanbc#238]
**When [Situation]?**
When we have:
- revised prototypes meshed with the draft IA
- proposed content priorities
- proposed timeline for content creation, reviews, revisions
- proposed indigenous engagement strategy

**I want to [Motivation]**
Meet with the CAS engagement and web team (Kristine, Louise, Sarah, Alana)

**So I can [Expected Outcome]**
- provide an overview of our project (Kristine is new in her role and has been provided background material)
- share and get feedback on our proposed strategies
- confirm a timeline and plan for developing content for MVP
- identify other teams or individuals who we will need to engage with
- identify approvals and blockers we need to be aware of
- start the conversation around measurement and KPIs

**Comment by apuns** [comment]
@hebertlaura to book a mtg for first week of july as Kristine is away next week/ in Van tomorrow

@sarahhamill advises capacity should allow for this mtg & follow up
