### ISSUE TITLE
Connect with CAS Data Team

### ISSUE THREAD

**Issue by hebertlaura** [bcgov/cleanbc#242]
When [Situation]?
When we have:
- revised prototypes meshed with the draft IA
- proposed priorities for content requiring data

I want to [Motivation]
Meet with the CAS data team (Hilary)

So I can [Expected Outcome]
- provide an update on the project
- share and get feedback on our proposed content requiring data
- explore data feasibility (esp. emissions graphs)
- identify timelines and next steps for data-related content

**Comment by apuns** [comment]
Update: Hilary Hop-Wo is on leave, suggested 2 team members to connect with, have rebooked for July 18. 

Have booked a separate check-in session with Hilary for July 28

**Comment by apuns** [comment]
Moved again -- meeting with HIlary's team members is now on July 14 @ 11 a
