### ISSUE TITLE
Online Service Feasibility Plan

### ISSUE THREAD

**Issue by harryol** [bcgov/cleanbc#244]
**As a [description of user]?**
A CleanBC Team member 

**I want to [functionality]**
Have a clear plan with the development team (Nate) on design feasibility 

**So that [benefit]**
- we meet accessibility implications 
- shared awareness between design and development 
- identify page types and reusable components 
 

**Additional context*
- Reusable service components (within new design and bring from Go Electric)

**Acceptance Criteria**
- Clear workflow plan for investigating feasibility 
- Set a cadence of check-ins for continuous investigation
- Identify examples of interactivity to see if they are feasible post launch (existing and new components)

**Comment by apuns** [comment]
Include in convo -- attending scrums/sprint ceremonies and updating tickets in Zenhub (to minimize rework for design team)

**Comment by apuns** [comment]
Initial mtg set up for July 12
