### ISSUE TITLE
Conversation with Program Area Re: Measurement 

### ISSUE THREAD

**Issue by harryol** [bcgov/cleanbc#245]
**As a [description of user]?**
CleanBC Team Member [...]

**I want to [functionality]**
Meet with behavioural insights team and program area[...]

**So that [benefit]**
We understand main program goals and service goals

**Acceptance Criteria**
- KPIs and objectives from the program area are identified
- Started to draft the data points for measurement planning

**Comment by harryol** [comment]
Conversation to be had after CAS meeting. 

Measurement mapping before we talk to Dan Pollock

**Comment by apuns** [comment]
Mtg booked for July 18 at 11 am
