### ISSUE TITLE
Mapping our research

### ISSUE THREAD

**Issue by hebertlaura** [bcgov/cleanbc#256]
**When [Situation]?**
We have conducted research in previous phases

**I want to [Motivation]**
Map the research to surface:
- the location and level of climate interest of participants
- patterns in their awareness, knowledge and interest in climate issues (using the iceberg model)

**So I can [Expected Outcome]**
Make informed decisions about who else we need to talk to
Plan our testing and intercepts to fill our gaps
Document research for the ongoing service model

**Comment by apuns** [comment]
Keep this to interest coding only

**Comment by harryol** [comment]
Revisit provincial map? See Wildfire BC example in mural.

**Comment by sidbhaskara** [comment]
Hi @AudeGueveneu - is this being reviewed by someone else than you? If yes, you can add them as assignee.

**Comment by AudeGueveneu** [comment]
Hi @apuns, 
I have completed mapping the research expect for the interviews below:
- CLBC201-01 is duplicated on the note taking sheet (one at 11:00:00 AM and one at 4:00:00 PM)
- CLBC203-01 (Notes doesn't seem to match the demographics)
- CLBC2-203-18, CLBC201-02 (missing notes)
