### ISSUE TITLE
Create a design system for CleanBC

### ISSUE THREAD

**Issue by hebertlaura** [bcgov/cleanbc#257]
**When [Situation]?**
We are ready to move to development in Wordpress

**I want to [Motivation]**
Create a design system of reusable components

**So I can [Expected Outcome]**
Give these to our developer for building
Our team can use them to build the pages
We have a flexible design system that meets our needs and the emergent needs of CleanBC
We have a consistent design system

**Comment by sidbhaskara** [comment]
Tickets to be added after conversations with Nate
