### ISSUE TITLE
Scope user testing 

### ISSUE THREAD

**Issue by sidbhaskara** [bcgov/cleanbc#278]
**When [Situation]?**
We are getting ready to test the content we published

**I want to [Motivation]**
Have an initial conversation with the CleanBC team about the content and design aspects
create reusable, standard approach for future use

**01 Define Goals** 

**02 Determine format and setting**
_Moderated_

**03 Determine number of users** 
_5-8?_

**04 Recruit the right participants** 
_Balance between rural and urban_

**05 Write tasks that match goals of study** 
_Exploratory Tasks_
_Specific Tasks_

**06 Conduct Pilot Study** 
_Test to fine-tune tasks and wording internally_

**07 Write a test plan**
_Study Goals_
_Logistics - time, dates, location, format_
_Participant Profiles_
_Tasks_
_Metrics, Questionnaires_

**So I can [Expected Outcome]**
Plan our user testing and TEST and VALIDATE our designs with citizens

**Comment by AudeGueveneu** [comment]
https://www.nngroup.com/articles/usability-test-checklist/
