### ISSUE TITLE
Identify image needs for the site

### ISSUE THREAD

**Issue by sidbhaskara** [bcgov/cleanbc#283]
**When [Situation]?**
We have approved content for a given page 

**I want to [Motivation]**
List out what images will be needed 

**So I can [Expected Outcome]**
so I can request that GCPE provide them

**Comment by sidbhaskara** [comment]
Add a task list to support this ticket

**Comment by harryaolson** [comment]
[Meeting with Allieren]

Unsplash is ok without people. Must be photography within British Columbia.

If there is people there is a general concern about licensing and release forms.

If we need to credit photographers see example:
https://descan.ca/sample-page/thank-you-unsplash

–––––

We have access to GCPE icons database to remain consistent and if work proceeds capacity.

–––––

Approval for hazard icons to be included in next week round of approvals.

–––––

Allieren and I have established a review process to move foreward to close this ticket.
