### ISSUE TITLE
Service design documentation and tips for other teams

### ISSUE THREAD

**Issue by sidbhaskara** [bcgov/cleanbc#322]
**When [Situation]?**

**I want to [Motivation]**

**So I can [Expected Outcome]**

**Comment by apuns** [comment]
@Allieren can you please clarify what this issue is asking for?

**Comment by Allieren** [comment]
@apuns I was adding both yourself and Laura and then had to join multiple meetings. I'm wondering if this is something we want to build out with the "when" "I want to" etc. and/or close it because documentation and a demo has happened.

**Comment by apuns** [comment]
@Allieren if you think there's more to do in terms of documentation we can definitely build it out! Otherwise i think it's fine to close, if you feel like you've got enough to go on with
