### ISSUE TITLE
Addressing corporate emissions

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#33]
**As a**
member of the general public in BC

**I want to**
information about what government is doing to regulate and reduce corporate emissions

**So that I can**
trust that government is taking actions to limit global warming.

**Additional context**
specifically show policy & regulation on corps; show corporate accountability

**Acceptance Criteria**
- Ensure this user story is also represented in the prototypes we are testing
- Prototype focused on the content model work

**Comment by apuns** [comment]
We've communicated about how gov is regulating industries but we don't have a category for "corporation" in our reporting -- we've laid a groundwork for industry but this can continue to evolve.
