### ISSUE TITLE
Giving Feedback on the CleanBC Plan

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#37]
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
access opportunities to give feedback on government programs and policies,

**So that [benefit]**
engage with the CleanBC plan by sharing my feedback.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #25
