### ISSUE TITLE
Understanding Payback Period of Wind Generators

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#38]
**As a [description of user]?**
British-Columbian looking to renovate/build my home,

**I want to [functionality]**
understand the payback period of installing  wind generators

**So that [benefit]**
determine if I wish to purchase and install them.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicates #92
