### ISSUE TITLE
Payback Period of Solar Panels

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#42]
**As a [description of user]?**
homeowner in BC,

**I want to [functionality]**
understand the payback period of installing solar panels,

**So that [benefit]**
determine if I wish to purchase and install them.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #92, closing
