### ISSUE TITLE
PRIORITY: Climate Actions Possible in Specific Regions

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#43]
**As a [description of user]?**
member of the general public in BC,	

**I want to [functionality]**
access information about climate actions that are possible where I live (certain actions face barriers in some areas such as heat pumps and EVs),	

**So that [benefit]**
I can take actions where I live that I can feel confident will make a difference.

**Additional context**
Corresponding summary: _take climate actions that are possible and feasible in my area of BC_

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #88, closing
