### ISSUE TITLE
Rebates Available to Renters

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#46]
**As a [description of user]?**
renter in BC, 

**I want to [functionality]**
access resources and rebates programs available to someone who rents

**So that [benefit]**
find actions I can take.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #76
