### ISSUE TITLE
Summary: see that gov's response to extreme weather is based in science

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#48]
**Summary:**
see that gov's response to extreme weather is based in science

**Specific user stories:**

**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
learn about the government's planned response to recent extreme weather events,

**So that [benefit]**
see if the response is based in science. 

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #115
