### ISSUE TITLE
Public Sharing of CleanBC Programs + Policies

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#49]
**As a [description of user]**
member of the general public in BC,

**I want to [functionality]**
be able to share a campaign or promotion of a specific program or policy on social media, directly from the CleanBC site,	

**So that [benefit]**
raise public awareness about government climate actions that are of interest to me.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
This is a dupe of issue #45, closing
