### ISSUE TITLE
PRIORITY: Gov Framework for Individual Sustainability Actions

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#57]
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
have a government framework to follow for individual sustainability actions,

**So that [benefit]**
feel confident that I'm taking meaningful action towards sustainability. 

**Additional context**
Relevant summary: have the government tell me which sustainability actions to prioritize

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
This dupes #39, closing
