### ISSUE TITLE
Summary: understand how the carbon tax helps with climate change

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#59]
**Summary:**
understand how the carbon tax helps with climate change

**Specific user stories:**
**As a [description of user]?**
member of the general public in BC,	

**I want to [functionality]**
understand how the carbon taxes helps to address climate change

**So that [benefit]**
understand government's choice to implement it.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicates #93, relates to #89
