### ISSUE TITLE
Wind Generators and Bird Migration

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#62]
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
member of the general public in BC,	

**So that [benefit]**
access information about the impact of wind generators on bird migration	and understand if the benefit to the environment is higher than the cost.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicates #92
