### ISSUE TITLE
Information About Solar Panels

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#63]
**As a [description of user]?**
British-Columbian looking to renovate/build a home,	

**I want to [functionality]**
access information about solar panels, their environmental cost and plans to recycle at end of lifecycle

**So that [benefit]**
How will this benefit the overall product goal?
understand if the benefit to the environment is higher than the cost.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #92, closing
