### ISSUE TITLE
Programs for Owners in a Strata

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#64]
**As a [description of user]?**
British-Columbian who own a strata unit

**I want to [functionality]**
access home improvement programs that are available to me (ie. rebates)

**So that [benefit]**
I can understand what is possible and feasible for my home.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #61
