### ISSUE TITLE
Impacts on Health

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#65]
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
access information about the impact of climate change & extreme weather on health

**So that [benefit]**
I can understand the impacts and how I might be personally affected

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
Combining with issue #65 which has a speculative "so i can" statement & closing this issue
