### ISSUE TITLE
CleanBC Metrics

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#66]
**As a [description of user]?**
member of the general public in BC,		

**I want to [functionality]**
see metrics attached to the CleanBC targets

**So that [benefit]**
I can understand whether we are meeting our goals

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicates #80, closing
