### ISSUE TITLE
Understand how extreme weather impacts health

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#68]
**Summary:**
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
access information about climate change & extreme weather negative impacts on health

**So that [benefit]**
understand the impacts and how I might be personally affected

**Additional context**
hypothetically: gain empathy? 
hypothetically: help people understand why it's important for gov to address climate change? 

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
This "so i can" statement is speculative so combining with issue #65 and closing #65
