### ISSUE TITLE
Government Addressing Impact of Climate Change on Health

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#69]
**As a [description of user]?**
member of the general public in BC,	

**I want to [functionality]**
access information about climate change & extreme weather negative impacts on health

**So that [benefit]**
understand the importance of government addressing it.

**Additional context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #68
