### ISSUE TITLE
PRIORITY: Case Studies

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#78]
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
access case studies of residents who have participated in government programs,

**So that [benefit]**
see proof of their effectiveness and understand if they might be a fit for me.

**Additional context**
Relevant summary: see people like me taking climate actions, so i can trust that they are possible and effective for me

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
duplicated by #51, closing
