### ISSUE TITLE
PRIORITY: Cost-Benefit

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#79]
**As a [description of user]?**
member of the general public in BC,	

**I want to [functionality]**
access the cost-benefit analysis of a policy or program decision,	

**So that [benefit]**
understand the research and rationale behind this policy or program and see that the government is being transparent.

**Additional context**
Relevant summary: see that government has addressed the risks and drawbacks of its climate plans

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
This is a dupe of issue #53, closing
