### ISSUE TITLE
PRIORITY: Hear from Climate Change Experts

### ISSUE THREAD

**Issue by jennamlynettemcneil** [bcgov/cleanbc#82]
**As a [description of user]?**
member of the general public in BC,

**I want to [functionality]**
hear about climate change from subject matter experts (rather than comms public servants or the media),	

**So that [benefit]**
How will this benefit the overall product goal?
trust that the information I am hearing is backed by science. 

**Additional context**
Relevant Summary: hear about climate change from subject matter experts; scientists

**Acceptance Criteria**
Agreed-upon confirmation of the requirements when done can be deemed as complete

**Comment by apuns** [comment]
Duplicated by #54, closing
