### ISSUE TITLE
NDA form for user research

### ISSUE THREAD

**Issue by apiluso-gov** [bcgov/cleanbc#99]
**As a [description of user]?**
User researcher and program stakeholder

**I want to [functionality]**
an NDA that binds user testing participants to not disclose any potentially sensitive information about the Go Electric program or its policies that may be viewed during upcoming research

**So that [benefit]**
there is no risk of information leaks before policies have been internally approved and officially published.

**Additional context**
Must be ready prior to user research sessions scheduled for May 17/18

**Acceptance Criteria**
- [x] NDA to be drafted
- [x] draft to be reviewed by Meg
- [x] draft to be reviewed by Audrey
- [x] changes to be sent back for revision
- [x] NDA to receive final approval and be ready for participants to sign

**Comment by meg-stiven** [comment]
@apiluso-gov I've reviewed the NDA and don't have any edits to suggest.
